# print('Enter your Name:')
# name = input()
# print('-'*50)
# name = input('Enter your Name:')
# print('Entered Name:',name,type(name))
print('-'*50)
# First_Number = input('Enter First Number')
# print('Entered Number:',First_Number,type(First_Number))
# Second_Number = input('Enter Second Number')
# print('Entered Number:',Second_Number,type(Second_Number))
# print('Addition:',First_Number+Second_Number)
print('-'*50)
First_Number = int(input('Enter First Number'))
print('Entered Number:',First_Number,type(First_Number))
Second_Number = int(input('Enter Second Number'))
print('Entered Number:',Second_Number,type(Second_Number))
print('Addition:',First_Number+Second_Number)
